name: Test 1.20.x

on:
  push:
    branches:
      - 1.20.x
  pull_request:
    branches: [ 1.20.x ]

jobs:
  main:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
      env:
        VERSION: indev-test
